repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0 # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies: ['prettier@3.8.0']
